[package]
name = "numrs"
version = "0.1.0"
edition = "2021"


[lib]
name = "numrs"

[profile.release]
opt-level = 3

[dependencies]
num = "0.4.3"
rand = "0.8.5"
rand_distr = "0.4.3"
rayon = "1.10.0"
thiserror = "2.0.9"
